require 'worldwide_taxon_presenter'

namespace :taxonomy do
  desc "Create draft taxons for worldwide taxonomy"
  task create_draft_taxons_for_worldwide_taxonomy: :environment do
    # From Whitehall:
    # WorldLocation.where(world_location_type_id: 1).map { |w| { slug: w.slug, name: w.name } }
    # and remove 'United Kingdom' as we do not want to create a taxon page for it
    countries = [
      { slug: "afghanistan", name: "Afghanistan" },
      { slug: "albania", name: "Albania" },
      { slug: "algeria", name: "Algeria" },
      { slug: "angola", name: "Angola" },
      { slug: "anguilla", name: "Anguilla" },
      { slug: "argentina", name: "Argentina" },
      { slug: "armenia", name: "Armenia" },
      { slug: "australia", name: "Australia" },
      { slug: "austria", name: "Austria" },
      { slug: "azerbaijan", name: "Azerbaijan" },
      { slug: "bahrain", name: "Bahrain" },
      { slug: "bangladesh", name: "Bangladesh" },
      { slug: "barbados", name: "Barbados" },
      { slug: "belarus", name: "Belarus" },
      { slug: "belgium", name: "Belgium" },
      { slug: "belize", name: "Belize" },
      { slug: "bolivia", name: "Bolivia" },
      { slug: "bosnia-and-herzegovina", name: "Bosnia and Herzegovina" },
      { slug: "botswana", name: "Botswana" },
      { slug: "brazil", name: "Brazil" },
      { slug: "british-antarctic-territory", name: "British Antarctic Territory" },
      { slug: "british-virgin-islands", name: "British Virgin Islands" },
      { slug: "brunei", name: "Brunei" },
      { slug: "bulgaria", name: "Bulgaria" },
      { slug: "burma", name: "Burma" },
      { slug: "cambodia", name: "Cambodia" },
      { slug: "cameroon", name: "Cameroon" },
      { slug: "canada", name: "Canada" },
      { slug: "cayman-islands", name: "Cayman Islands" },
      { slug: "chile", name: "Chile" },
      { slug: "china", name: "China" },
      { slug: "colombia", name: "Colombia" },
      { slug: "costa-rica", name: "Costa Rica" },
      { slug: "croatia", name: "Croatia" },
      { slug: "cuba", name: "Cuba" },
      { slug: "cyprus", name: "Cyprus" },
      { slug: "czech-republic", name: "Czech Republic" },
      { slug: "democratic-republic-of-the-congo", name: "Democratic Republic of Congo" },
      { slug: "denmark", name: "Denmark" },
      { slug: "dominican-republic", name: "Dominican Republic" },
      { slug: "ecuador", name: "Ecuador" },
      { slug: "egypt", name: "Egypt" },
      { slug: "eritrea", name: "Eritrea" },
      { slug: "estonia", name: "Estonia" },
      { slug: "ethiopia", name: "Ethiopia" },
      { slug: "fiji", name: "Fiji" },
      { slug: "finland", name: "Finland" },
      { slug: "france", name: "France" },
      { slug: "gambia", name: "Gambia" },
      { slug: "georgia", name: "Georgia" },
      { slug: "germany", name: "Germany" },
      { slug: "ghana", name: "Ghana" },
      { slug: "greece", name: "Greece" },
      { slug: "guatemala", name: "Guatemala" },
      { slug: "guyana", name: "Guyana" },
      { slug: "holy-see", name: "Holy See" },
      { slug: "honduras", name: "Honduras" },
      { slug: "hong-kong", name: "Hong Kong" },
      { slug: "hungary", name: "Hungary" },
      { slug: "iceland", name: "Iceland" },
      { slug: "india", name: "India" },
      { slug: "indonesia", name: "Indonesia" },
      { slug: "iran", name: "Iran" },
      { slug: "iraq", name: "Iraq" },
      { slug: "ireland", name: "Ireland" },
      { slug: "israel", name: "Israel" },
      { slug: "italy", name: "Italy" },
      { slug: "jamaica", name: "Jamaica" },
      { slug: "japan", name: "Japan" },
      { slug: "jordan", name: "Jordan" },
      { slug: "kazakhstan", name: "Kazakhstan" },
      { slug: "kenya", name: "Kenya" },
      { slug: "kosovo", name: "Kosovo" },
      { slug: "kuwait", name: "Kuwait" },
      { slug: "laos", name: "Laos" },
      { slug: "latvia", name: "Latvia" },
      { slug: "lebanon", name: "Lebanon" },
      { slug: "libya", name: "Libya" },
      { slug: "lithuania", name: "Lithuania" },
      { slug: "luxembourg", name: "Luxembourg" },
      { slug: "macedonia", name: "Macedonia" },
      { slug: "madagascar", name: "Madagascar" },
      { slug: "malawi", name: "Malawi" },
      { slug: "malaysia", name: "Malaysia" },
      { slug: "maldives", name: "Maldives" },
      { slug: "mali", name: "Mali" },
      { slug: "malta", name: "Malta" },
      { slug: "mauritius", name: "Mauritius" },
      { slug: "mexico", name: "Mexico" },
      { slug: "moldova", name: "Moldova" },
      { slug: "mongolia", name: "Mongolia" },
      { slug: "montenegro", name: "Montenegro" },
      { slug: "montserrat", name: "Montserrat" },
      { slug: "morocco", name: "Morocco" },
      { slug: "mozambique", name: "Mozambique" },
      { slug: "namibia", name: "Namibia" },
      { slug: "nepal", name: "Nepal" },
      { slug: "netherlands", name: "Netherlands" },
      { slug: "new-zealand", name: "New Zealand" },
      { slug: "nigeria", name: "Nigeria" },
      { slug: "north-korea", name: "North Korea" },
      { slug: "norway", name: "Norway" },
      { slug: "oman", name: "Oman" },
      { slug: "pakistan", name: "Pakistan" },
      { slug: "panama", name: "Panama" },
      { slug: "papua-new-guinea", name: "Papua New Guinea" },
      { slug: "peru", name: "Peru" },
      { slug: "philippines", name: "Philippines" },
      { slug: "poland", name: "Poland" },
      { slug: "portugal", name: "Portugal" },
      { slug: "qatar", name: "Qatar" },
      { slug: "romania", name: "Romania" },
      { slug: "russia", name: "Russia" },
      { slug: "rwanda", name: "Rwanda" },
      { slug: "saudi-arabia", name: "Saudi Arabia" },
      { slug: "senegal", name: "Senegal" },
      { slug: "serbia", name: "Serbia" },
      { slug: "seychelles", name: "Seychelles" },
      { slug: "sierra-leone", name: "Sierra Leone" },
      { slug: "singapore", name: "Singapore" },
      { slug: "slovakia", name: "Slovakia" },
      { slug: "slovenia", name: "Slovenia" },
      { slug: "solomon-islands", name: "Solomon Islands" },
      { slug: "somalia", name: "Somalia" },
      { slug: "south-africa", name: "South Africa" },
      { slug: "south-korea", name: "South Korea" },
      { slug: "south-sudan", name: "South Sudan" },
      { slug: "spain", name: "Spain" },
      { slug: "sri-lanka", name: "Sri Lanka" },
      { slug: "sudan", name: "Sudan" },
      { slug: "sweden", name: "Sweden" },
      { slug: "switzerland", name: "Switzerland" },
      { slug: "syria", name: "Syria" },
      { slug: "taiwan", name: "Taiwan" },
      { slug: "tajikistan", name: "Tajikistan" },
      { slug: "tanzania", name: "Tanzania" },
      { slug: "thailand", name: "Thailand" },
      { slug: "timor-leste", name: "Timor Leste" },
      { slug: "trinidad-and-tobago", name: "Trinidad and Tobago" },
      { slug: "tunisia", name: "Tunisia" },
      { slug: "turkey", name: "Turkey" },
      { slug: "turkmenistan", name: "Turkmenistan" },
      { slug: "turks-and-caicos-islands", name: "Turks and Caicos Islands" },
      { slug: "uganda", name: "Uganda" },
      { slug: "ukraine", name: "Ukraine" },
      { slug: "united-arab-emirates", name: "United Arab Emirates" },
      { slug: "uruguay", name: "Uruguay" },
      { slug: "usa", name: "USA" },
      { slug: "uzbekistan", name: "Uzbekistan" },
      { slug: "venezuela", name: "Venezuela" },
      { slug: "vietnam", name: "Vietnam" },
      { slug: "yemen", name: "Yemen" },
      { slug: "zambia", name: "Zambia" },
      { slug: "zimbabwe", name: "Zimbabwe" },
      { slug: "andorra", name: "Andorra" },
      { slug: "antigua-and-barbuda", name: "Antigua and Barbuda" },
      { slug: "bahamas", name: "Bahamas" },
      { slug: "benin", name: "Benin" },
      { slug: "bhutan", name: "Bhutan" },
      { slug: "burkina-faso", name: "Burkina Faso" },
      { slug: "cape-verde", name: "Cape Verde" },
      { slug: "comoros", name: "Comoros" },
      { slug: "congo", name: "Congo" },
      { slug: "cote-d-ivoire", name: "Cote d’Ivoire" },
      { slug: "djibouti", name: "Djibouti" },
      { slug: "dominica", name: "Dominica" },
      { slug: "equatorial-guinea", name: "Equatorial Guinea" },
      { slug: "grenada", name: "Grenada" },
      { slug: "guinea-bissau", name: "Guinea-Bissau" },
      { slug: "haiti", name: "Haiti" },
      { slug: "kiribati", name: "Kiribati" },
      { slug: "lesotho", name: "Lesotho" },
      { slug: "liberia", name: "Liberia" },
      { slug: "liechtenstein", name: "Liechtenstein" },
      { slug: "macao", name: "Macao" },
      { slug: "marshall-islands", name: "Marshall Islands" },
      { slug: "micronesia", name: "Micronesia" },
      { slug: "nauru", name: "Nauru" },
      { slug: "nicaragua", name: "Nicaragua" },
      { slug: "niger", name: "Niger" },
      { slug: "the-occupied-palestinian-territories", name: "The Occupied Palestinian Territories" },
      { slug: "palau", name: "Palau" },
      { slug: "paraguay", name: "Paraguay" },
      { slug: "samoa", name: "Samoa" },
      { slug: "sao-tome-and-principe", name: "São Tomé and Principe" },
      { slug: "st-kitts-and-nevis", name: "St Kitts and Nevis" },
      { slug: "st-vincent-and-the-grenadines", name: "St Vincent and The Grenadines" },
      { slug: "suriname", name: "Suriname" },
      { slug: "swaziland", name: "Swaziland" },
      { slug: "togo", name: "Togo" },
      { slug: "tuvalu", name: "Tuvalu" },
      { slug: "vanuatu", name: "Vanuatu" },
      { slug: "bermuda", name: "Bermuda" },
      { slug: "burundi", name: "Burundi" },
      { slug: "el-salvador", name: "El Salvador" },
      { slug: "falkland-islands", name: "Falkland Islands" },
      { slug: "guinea", name: "Guinea" },
      { slug: "st-helena-ascension-and-tristan-da-cunha", name: "St Helena, Ascension and Tristan da Cunha" },
      { slug: "st-lucia", name: "St Lucia" },
      { slug: "kyrgyzstan", name: "Kyrgyzstan" },
      { slug: "pitcairn-island", name: "Pitcairn Island" },
      { slug: "chad", name: "Chad" },
      { slug: "mauritania", name: "Mauritania" },
      { slug: "american-samoa", name: "American Samoa" },
      { slug: "aruba", name: "Aruba" },
      { slug: "bonaire-st-eustatius-saba", name: "Bonaire/St Eustatius/Saba" },
      { slug: "central-african-republic", name: "Central African Republic" },
      { slug: "curacao", name: "Curaçao" },
      { slug: "french-guiana", name: "French Guiana" },
      { slug: "french-polynesia", name: "French Polynesia" },
      { slug: "gabon", name: "Gabon" },
      { slug: "gibraltar", name: "Gibraltar" },
      { slug: "guadeloupe", name: "Guadeloupe" },
      { slug: "martinique", name: "Martinique" },
      { slug: "mayotte", name: "Mayotte" },
      { slug: "monaco", name: "Monaco" },
      { slug: "new-caledonia", name: "New Caledonia" },
      { slug: "reunion", name: "Réunion" },
      { slug: "san-marino", name: "San Marino" },
      { slug: "south-georgia-and-south-sandwich-islands", name: "South Georgia and the South Sandwich Islands" },
      { slug: "st-maarten", name: "St Maarten" },
      { slug: "st-pierre-and-miquelon", name: "St Pierre & Miquelon" },
      { slug: "tonga", name: "Tonga" },
      { slug: "wallis-and-futuna", name: "Wallis and Futuna" },
      { slug: "western-sahara", name: "Western Sahara" },
      { slug: "st-martin", name: "St Martin" },
    ]

    eu_country_slugs = [
      "austria",
      "belgium",
      "bulgaria",
      "croatia",
      "cyprus",
      "czech-republic",
      "denmark",
      "estonia",
      "finland",
      "france",
      "germany",
      "greece",
      "hungary",
      "ireland",
      "italy",
      "latvia",
      "lithuania",
      "luxembourg",
      "malta",
      "netherlands",
      "poland",
      "portugal",
      "romania",
      "slovakia",
      "slovenia",
      "spain",
      "sweden",
    ]
    eu_countries = countries.select { |c| eu_country_slugs.include?(c[:slug]) }

    generic_taxons = [
      {
        title: "Emergency help for British nationals",
        description: "Get help if you're the victim of crime, you've been arrested, or are affected by a crisis abroad.",
        content_id: "26adf294-1b3d-49cf-a465-46fe132511e9",
        slug: "emergency-help-for-british-nationals",
      },
      {
        title: "Passports and emergency travel documents",
        description: "Includes how to cancel a lost passport, renew a passport and apply for an emergency travel document.",
        content_id: "374e8288-d58c-4914-b81b-e66ab4803925",
        slug: "passports-and-emergency-travel-documents",
      },
      {
        title: "Travelling to COUNTRY",
        description: "Includes travel advice and how to get married abroad.",
        content_id: "4fe5a04b-9f68-4644-abb4-1f54c93f50e7",
        slug: "travelling-to-COUNTRY",
      },
      {
        title: "Coming to the UK",
        description: "Get a visa to study, work or visit the UK.",
        content_id: "d0e61780-6962-40aa-bb57-298f35187e4f",
        slug: "coming-to-the-uk",
      },
      {
        title: "Living in COUNTRY",
        description: "Includes how to access healthcare, get a document legalised, lists of lawyers and how to vote abroad.",
        content_id: "f4450d6d-ae53-4da0-88e5-cfe32c76a5ee",
        slug: "living-in-COUNTRY",
      },
      {
        title: "Tax, benefits, pensions and working abroad",
        description: "Includes how to pay tax, claim State Pension and get tax credits abroad.",
        content_id: "382360ab-c4cf-4e2a-b043-0cfa395f1d0b",
        slug: "tax-benefits-pensions-and-working-abroad",
      },
      {
        title: "Birth, death and marriage abroad",
        description: "Includes how to get married, list of funeral directors and how to register a birth abroad.",
        content_id: "eed5b92e-8279-4ca9-a141-5c35ed22fcf1",
        slug: "birth-death-and-marriage-abroad",
      },
      {
        title: "News and events",
        description: "Find out about the UK government's diplomatic, security and development work in COUNTRY.",
        content_id: "0c5945fc-f65c-4bd1-a664-9e302f3d448c",
        slug: "news-and-events",
      },
      {
        title: "Trade and invest",
        description: "Includes investing and setting up a business in the UK and doing business in COUNTRY.",
        content_id: "172c9d39-445f-4501-b0b2-1d527cc7cabc",
        slug: "trade-and-invest",
      },
      {
        title: "British embassy or high commission",
        description: "Includes contact details, opening hours and consular fees and local services.",
        content_id: "0d729f86-e07e-4271-a505-9f80954eeeed",
        slug: "british-embassy-or-high-commission",
      },
    ]

    brexit_taxon = {
      title: "Brexit",
      description: "Latest information and guidance on the UK exiting the EU.",
      content_id: "d4c4d91d-fbe7-4eff-bd57-189138c626c9",
      slug: "brexit",
    }

    all_taxons = Services
      .publishing_api
      .get_content_items(
        document_type: 'taxon',
        per_page: 5000,
      ).to_h["results"]
    all_taxon_base_paths = all_taxons.map { |t| t["base_path"] }

    taxons_to_create = []

    countries.each do |country|
      generic_taxons.each do |taxon|
        taxon_params = WorldwideTaxonPresenter.new(country, taxon, all_taxons).present
        taxon = Taxon.new(taxon_params)
        taxons_to_create.push(taxon)
      end
    end

    eu_countries.each do |country|
      taxon_params = WorldwideTaxonPresenter.new(country, brexit_taxon, all_taxons).present
      taxon = Taxon.new(taxon_params)
      taxons_to_create.push(taxon)
    end

    taxons_to_create.each do |taxon|
      begin
        if all_taxon_base_paths.include?(taxon.base_path)
          puts "Skipping taxon for #{taxon.base_path}, already exists"
        elsif taxon.valid?
          puts "Creating taxon for #{taxon.base_path}"
          Taxonomy::UpdateTaxon.call(taxon: taxon)
        else
          puts "Error: Invalid taxon for #{taxon.base_path}"
          puts taxon.errors
        end
      rescue => e
        puts "Error: Failed to create taxon for #{taxon.base_path}, #{e.message}"
      end
    end
  end
end
