namespace :taxonomy do
  desc "Update country taxon summary for worldwide taxonomy"
  task update_country_taxon_summary_for_worldwide_taxonomy: :environment do
    # country slugs from Whitehall
    country_slugs = [
      "afghanistan",
      "albania",
      "algeria",
      "angola",
      "anguilla",
      "argentina",
      "armenia",
      "australia",
      "austria",
      "azerbaijan",
      "bahrain",
      "bangladesh",
      "barbados",
      "belarus",
      "belgium",
      "belize",
      "bolivia",
      "bosnia-and-herzegovina",
      "botswana",
      "brazil",
      "british-antarctic-territory",
      "british-virgin-islands",
      "brunei",
      "bulgaria",
      "burma",
      "cambodia",
      "cameroon",
      "canada",
      "cayman-islands",
      "chile",
      "china",
      "colombia",
      "costa-rica",
      "croatia",
      "cuba",
      "cyprus",
      "czech-republic",
      "democratic-republic-of-the-congo",
      "denmark",
      "dominican-republic",
      "ecuador",
      "egypt",
      "eritrea",
      "estonia",
      "ethiopia",
      "fiji",
      "finland",
      "france",
      "gambia",
      "georgia",
      "germany",
      "ghana",
      "greece",
      "guatemala",
      "guyana",
      "holy-see",
      "honduras",
      "hong-kong",
      "hungary",
      "iceland",
      "india",
      "indonesia",
      "iran",
      "iraq",
      "ireland",
      "israel",
      "italy",
      "jamaica",
      "japan",
      "jordan",
      "kazakhstan",
      "kenya",
      "kosovo",
      "kuwait",
      "laos",
      "latvia",
      "lebanon",
      "libya",
      "lithuania",
      "luxembourg",
      "macedonia",
      "madagascar",
      "malawi",
      "malaysia",
      "maldives",
      "mali",
      "malta",
      "mauritius",
      "mexico",
      "moldova",
      "mongolia",
      "montenegro",
      "montserrat",
      "morocco",
      "mozambique",
      "namibia",
      "nepal",
      "netherlands",
      "new-zealand",
      "nigeria",
      "north-korea",
      "norway",
      "oman",
      "pakistan",
      "panama",
      "papua-new-guinea",
      "peru",
      "philippines",
      "poland",
      "portugal",
      "qatar",
      "romania",
      "russia",
      "rwanda",
      "saudi-arabia",
      "senegal",
      "serbia",
      "seychelles",
      "sierra-leone",
      "singapore",
      "slovakia",
      "slovenia",
      "solomon-islands",
      "somalia",
      "south-africa",
      "south-korea",
      "south-sudan",
      "spain",
      "sri-lanka",
      "sudan",
      "sweden",
      "switzerland",
      "syria",
      "taiwan",
      "tajikistan",
      "tanzania",
      "thailand",
      "timor-leste",
      "trinidad-and-tobago",
      "tunisia",
      "turkey",
      "turkmenistan",
      "turks-and-caicos-islands",
      "uganda",
      "ukraine",
      "united-arab-emirates",
      "uruguay",
      "usa",
      "uzbekistan",
      "venezuela",
      "vietnam",
      "yemen",
      "zambia",
      "zimbabwe",
      "andorra",
      "antigua-and-barbuda",
      "bahamas",
      "benin",
      "bhutan",
      "burkina-faso",
      "cape-verde",
      "comoros",
      "congo",
      "cote-d-ivoire",
      "djibouti",
      "dominica",
      "equatorial-guinea",
      "grenada",
      "guinea-bissau",
      "haiti",
      "kiribati",
      "lesotho",
      "liberia",
      "liechtenstein",
      "macao",
      "marshall-islands",
      "micronesia",
      "nauru",
      "nicaragua",
      "niger",
      "the-occupied-palestinian-territories",
      "palau",
      "paraguay",
      "samoa",
      "sao-tome-and-principe",
      "st-kitts-and-nevis",
      "st-vincent-and-the-grenadines",
      "suriname",
      "swaziland",
      "togo",
      "tuvalu",
      "vanuatu",
      "bermuda",
      "burundi",
      "el-salvador",
      "falkland-islands",
      "guinea",
      "st-helena-ascension-and-tristan-da-cunha",
      "st-lucia",
      "kyrgyzstan",
      "pitcairn-island",
      "chad",
      "mauritania",
      "american-samoa",
      "aruba",
      "bonaire-st-eustatius-saba",
      "central-african-republic",
      "curacao",
      "french-guiana",
      "french-polynesia",
      "gabon",
      "gibraltar",
      "guadeloupe",
      "martinique",
      "mayotte",
      "monaco",
      "new-caledonia",
      "reunion",
      "san-marino",
      "south-georgia-and-south-sandwich-islands",
      "st-maarten",
      "st-pierre-and-miquelon",
      "tonga",
      "wallis-and-futuna",
      "western-sahara",
      "st-martin",
    ]

    all_taxons = Services
      .publishing_api
      .get_content_items(
        document_type: 'taxon',
        per_page: 10_000,
      ).to_h["results"]

    country_taxons = country_slugs.map do |slug|
      content_item = all_taxons.find { |t| t["base_path"] == "/world/#{slug}" }
      Taxonomy::BuildTaxon.call(content_id: content_item["content_id"])
    end

    country_taxons.each do |taxon|
      country_name = taxon.title.gsub(" and the UK", "")
      description_ending = " and #{country_name}."

      unless taxon.description.ends_with?(description_ending)
        taxon.description = taxon.description.gsub(/.$/, description_ending)
      end

      begin
        puts "Updating description for #{taxon.base_path}"
        Taxonomy::UpdateTaxon.call(taxon: taxon)
        Services.publishing_api.publish(taxon.content_id) if taxon.published?
      rescue StandardError => e
        puts "Error for #{taxon.base_path}: #{e.message}"
      end
    end
  end
end
