namespace :taxonomy do
  desc "Update titles for world location taxons"
  task update_titles_for_world_location_taxons: :environment do
    # location slugs and names from Whitehall
    location_slugs_and_names = {
      'afghanistan' => 'Afghanistan',
      'albania' => 'Albania',
      'algeria' => 'Algeria',
      'american-samoa' => 'American Samoa',
      'andorra' => 'Andorra',
      'angola' => 'Angola',
      'anguilla' => 'Anguilla',
      'antigua-and-barbuda' => 'Antigua and Barbuda',
      'argentina' => 'Argentina',
      'armenia' => 'Armenia',
      'aruba' => 'Aruba',
      'australia' => 'Australia',
      'austria' => 'Austria',
      'azerbaijan' => 'Azerbaijan',
      'bahamas' => 'Bahamas',
      'bahrain' => 'Bahrain',
      'bangladesh' => 'Bangladesh',
      'barbados' => 'Barbados',
      'belarus' => 'Belarus',
      'belgium' => 'Belgium',
      'belize' => 'Belize',
      'benin' => 'Benin',
      'bermuda' => 'Bermuda',
      'bhutan' => 'Bhutan',
      'bolivia' => 'Bolivia',
      'bonaire-st-eustatius-saba' => 'Bonaire/St Eustatius/Saba',
      'bosnia-and-herzegovina' => 'Bosnia and Herzegovina',
      'botswana' => 'Botswana',
      'brazil' => 'Brazil',
      'british-antarctic-territory' => 'British Antarctic Territory',
      'british-indian-ocean-territory' => 'British Indian Ocean Territory',
      'british-virgin-islands' => 'British Virgin Islands',
      'brunei' => 'Brunei',
      'bulgaria' => 'Bulgaria',
      'burkina-faso' => 'Burkina Faso',
      'burma' => 'Burma',
      'burundi' => 'Burundi',
      'cambodia' => 'Cambodia',
      'cameroon' => 'Cameroon',
      'canada' => 'Canada',
      'cape-verde' => 'Cape Verde',
      'cayman-islands' => 'Cayman Islands',
      'central-african-republic' => 'Central African Republic',
      'chad' => 'Chad',
      'chile' => 'Chile',
      'china' => 'China',
      'colombia' => 'Colombia',
      'comoros' => 'Comoros',
      'congo' => 'Congo',
      'costa-rica' => 'Costa Rica',
      'cote-d-ivoire' => 'Cote d’Ivoire',
      'croatia' => 'Croatia',
      'cuba' => 'Cuba',
      'curacao' => 'Curaçao',
      'cyprus' => 'Cyprus',
      'czech-republic' => 'Czech Republic',
      'democratic-republic-of-the-congo' => 'Democratic Republic of the Congo',
      'denmark' => 'Denmark',
      'djibouti' => 'Djibouti',
      'dominica' => 'Dominica',
      'dominican-republic' => 'Dominican Republic',
      'ecuador' => 'Ecuador',
      'egypt' => 'Egypt',
      'el-salvador' => 'El Salvador',
      'equatorial-guinea' => 'Equatorial Guinea',
      'eritrea' => 'Eritrea',
      'estonia' => 'Estonia',
      'ethiopia' => 'Ethiopia',
      'falkland-islands' => 'Falkland Islands',
      'fiji' => 'Fiji',
      'finland' => 'Finland',
      'france' => 'France',
      'french-guiana' => 'French Guiana',
      'french-polynesia' => 'French Polynesia',
      'gabon' => 'Gabon',
      'gambia' => 'Gambia',
      'georgia' => 'Georgia',
      'germany' => 'Germany',
      'ghana' => 'Ghana',
      'gibraltar' => 'Gibraltar',
      'greece' => 'Greece',
      'grenada' => 'Grenada',
      'guadeloupe' => 'Guadeloupe',
      'guatemala' => 'Guatemala',
      'guinea' => 'Guinea',
      'guinea-bissau' => 'Guinea-Bissau',
      'guyana' => 'Guyana',
      'haiti' => 'Haiti',
      'holy-see' => 'Holy See',
      'honduras' => 'Honduras',
      'hong-kong' => 'Hong Kong',
      'hungary' => 'Hungary',
      'iceland' => 'Iceland',
      'india' => 'India',
      'indonesia' => 'Indonesia',
      'iran' => 'Iran',
      'iraq' => 'Iraq',
      'ireland' => 'Ireland',
      'israel' => 'Israel',
      'italy' => 'Italy',
      'jamaica' => 'Jamaica',
      'japan' => 'Japan',
      'jordan' => 'Jordan',
      'kazakhstan' => 'Kazakhstan',
      'kenya' => 'Kenya',
      'kiribati' => 'Kiribati',
      'kosovo' => 'Kosovo',
      'kuwait' => 'Kuwait',
      'kyrgyzstan' => 'Kyrgyzstan',
      'laos' => 'Laos',
      'latvia' => 'Latvia',
      'lebanon' => 'Lebanon',
      'lesotho' => 'Lesotho',
      'liberia' => 'Liberia',
      'libya' => 'Libya',
      'liechtenstein' => 'Liechtenstein',
      'lithuania' => 'Lithuania',
      'luxembourg' => 'Luxembourg',
      'macao' => 'Macao',
      'macedonia' => 'Macedonia',
      'madagascar' => 'Madagascar',
      'malawi' => 'Malawi',
      'malaysia' => 'Malaysia',
      'maldives' => 'Maldives',
      'mali' => 'Mali',
      'malta' => 'Malta',
      'marshall-islands' => 'Marshall Islands',
      'martinique' => 'Martinique',
      'mauritania' => 'Mauritania',
      'mauritius' => 'Mauritius',
      'mayotte' => 'Mayotte',
      'mexico' => 'Mexico',
      'micronesia' => 'Micronesia',
      'moldova' => 'Moldova',
      'monaco' => 'Monaco',
      'mongolia' => 'Mongolia',
      'montenegro' => 'Montenegro',
      'montserrat' => 'Montserrat',
      'morocco' => 'Morocco',
      'mozambique' => 'Mozambique',
      'namibia' => 'Namibia',
      'nauru' => 'Nauru',
      'nepal' => 'Nepal',
      'netherlands' => 'Netherlands',
      'new-caledonia' => 'New Caledonia',
      'new-zealand' => 'New Zealand',
      'nicaragua' => 'Nicaragua',
      'niger' => 'Niger',
      'nigeria' => 'Nigeria',
      'north-korea' => 'North Korea',
      'norway' => 'Norway',
      'oman' => 'Oman',
      'pakistan' => 'Pakistan',
      'palau' => 'Palau',
      'panama' => 'Panama',
      'papua-new-guinea' => 'Papua New Guinea',
      'paraguay' => 'Paraguay',
      'peru' => 'Peru',
      'philippines' => 'Philippines',
      'pitcairn-island' => 'Pitcairn Island',
      'poland' => 'Poland',
      'portugal' => 'Portugal',
      'qatar' => 'Qatar',
      'reunion' => 'Réunion',
      'romania' => 'Romania',
      'russia' => 'Russia',
      'rwanda' => 'Rwanda',
      'saint-barthelemy' => 'Saint-Barthélemy',
      'samoa' => 'Samoa',
      'san-marino' => 'San Marino',
      'sao-tome-and-principe' => 'São Tomé and Principe',
      'saudi-arabia' => 'Saudi Arabia',
      'senegal' => 'Senegal',
      'serbia' => 'Serbia',
      'seychelles' => 'Seychelles',
      'sierra-leone' => 'Sierra Leone',
      'singapore' => 'Singapore',
      'slovakia' => 'Slovakia',
      'slovenia' => 'Slovenia',
      'solomon-islands' => 'Solomon Islands',
      'somalia' => 'Somalia',
      'south-africa' => 'South Africa',
      'south-georgia-and-south-sandwich-islands' => 'South Georgia and the South Sandwich Islands',
      'south-korea' => 'South Korea',
      'south-sudan' => 'South Sudan',
      'spain' => 'Spain',
      'sri-lanka' => 'Sri Lanka',
      'st-helena-ascension-and-tristan-da-cunha' => 'St Helena, Ascension and Tristan da Cunha',
      'st-kitts-and-nevis' => 'St Kitts and Nevis',
      'st-lucia' => 'St Lucia',
      'st-maarten' => 'St Maarten',
      'st-martin' => 'St Martin',
      'st-pierre-and-miquelon' => 'St Pierre & Miquelon',
      'st-vincent-and-the-grenadines' => 'St Vincent and The Grenadines',
      'sudan' => 'Sudan',
      'suriname' => 'Suriname',
      'swaziland' => 'Swaziland',
      'sweden' => 'Sweden',
      'switzerland' => 'Switzerland',
      'syria' => 'Syria',
      'taiwan' => 'Taiwan',
      'tajikistan' => 'Tajikistan',
      'tanzania' => 'Tanzania',
      'thailand' => 'Thailand',
      'the-occupied-palestinian-territories' => 'The Occupied Palestinian Territories',
      'timor-leste' => 'Timor Leste',
      'togo' => 'Togo',
      'tonga' => 'Tonga',
      'trinidad-and-tobago' => 'Trinidad and Tobago',
      'tunisia' => 'Tunisia',
      'turkey' => 'Turkey',
      'turkmenistan' => 'Turkmenistan',
      'turks-and-caicos-islands' => 'Turks and Caicos Islands',
      'tuvalu' => 'Tuvalu',
      'uganda' => 'Uganda',
      'ukraine' => 'Ukraine',
      'united-arab-emirates' => 'United Arab Emirates',
      'united-kingdom' => 'United Kingdom',
      'uruguay' => 'Uruguay',
      'usa' => 'USA',
      'uzbekistan' => 'Uzbekistan',
      'vanuatu' => 'Vanuatu',
      'venezuela' => 'Venezuela',
      'vietnam' => 'Vietnam',
      'wallis-and-futuna' => 'Wallis and Futuna',
      'western-sahara' => 'Western Sahara',
      'yemen' => 'Yemen',
      'zambia' => 'Zambia',
      'zimbabwe' => 'Zimbabwe',
    }

    all_taxons = Services
      .publishing_api
      .get_content_items(
        document_type: 'taxon',
        per_page: 10_000,
      ).to_h["results"]

    location_slugs_and_names.each do |slug, location_name|
      puts "Fetching taxon for /world/#{slug}"
      content_item = all_taxons.find { |t| t["base_path"] == "/world/#{slug}" }
      if content_item.nil?
        puts "*** No taxon for /world/#{slug}"
      else
        taxon = Taxonomy::BuildTaxon.call(content_id: content_item["content_id"])
        taxon.title = "UK help and services in #{location_name}"
        taxon.internal_name = "UK help and services in #{location_name}"

        begin
          puts "Updating title and internal name for #{taxon.base_path}"
          Taxonomy::UpdateTaxon.call(taxon: taxon)
          Services.publishing_api.publish(taxon.content_id) if taxon.published?
        rescue StandardError => e
          puts "Error for #{taxon.base_path}: #{e.message}"
        end
      end
    end
  end
end
