default: &default
  adapter: postgresql
  encoding: unicode
  template: template0
  pool: 5

development:
  <<: *default
  database: content_tagger_development
  url: <%= ENV["DATABASE_URL"] %>

test:
  <<: *default
  database: content_tagger_test
  url: <%= ENV["TEST_DATABASE_URL"] %>

# In production the `DATABASE_URL` environment variable is automatically used.
